# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Submenu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Submenu
  pod 'SDWebImage', '~> 4.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry', '~> 1.0'
end
